// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1VoroninaVar5;

#nullable disable

namespace Task1VoroninaVar5.Migrations
{
    [DbContext(typeof(CityContext))]
    partial class CityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Task1VoroninaVar5.House", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("flatNum")
                        .HasColumnType("int");

                    b.Property<int>("streetId")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("streetId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = "3-a",
                            flatNum = 2000,
                            streetId = 11,
                            year = 2000
                        },
                        new
                        {
                            Id = "4-б",
                            flatNum = 36,
                            streetId = 11,
                            year = 1976
                        },
                        new
                        {
                            Id = "75-с",
                            flatNum = 355,
                            streetId = 11,
                            year = 2010
                        },
                        new
                        {
                            Id = "14",
                            flatNum = 90,
                            streetId = 541,
                            year = 1955
                        },
                        new
                        {
                            Id = "43",
                            flatNum = 50,
                            streetId = 541,
                            year = 1910
                        },
                        new
                        {
                            Id = "55",
                            flatNum = 66,
                            streetId = 541,
                            year = 1999
                        },
                        new
                        {
                            Id = "17-б",
                            flatNum = 466,
                            streetId = 55,
                            year = 1980
                        },
                        new
                        {
                            Id = "100-л",
                            flatNum = 800,
                            streetId = 55,
                            year = 2022
                        },
                        new
                        {
                            Id = "1789-у",
                            flatNum = 10,
                            streetId = 55,
                            year = 1988
                        });
                });

            modelBuilder.Entity("Task1VoroninaVar5.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Streets");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Name = "Michurina"
                        },
                        new
                        {
                            Id = 541,
                            Name = "Rakhova"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Veselaya"
                        });
                });

            modelBuilder.Entity("Task1VoroninaVar5.House", b =>
                {
                    b.HasOne("Task1VoroninaVar5.Street", null)
                        .WithMany("Users")
                        .HasForeignKey("streetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Task1VoroninaVar5.Street", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
